### ISSUE TITLE
one image one checkpoint？

### ISSUE THREAD

**Issue by shang106121** [danielroich/PTI#1]
Hello,
I have a question. When we fine-tune the generator, do we need to save a corresponding model parameter for each image?

**Comment by danielroich** [comment]
Hi Shang,
The PTI procedure saves 2 outputs, the vector "w" which is used as the inversion for the input image, and the model itself after changing the weights to better suit the specified image.

The "run_PTI" method accepts an argument called "use_multi_id". If it is set to True, then PTI will create *One* Model(Tuned StyleGAN) for all of the images. If it is set to False(Default) PTI will save several models, one model for each image.

Hope it answers your question,
Daniel

**Comment by shang106121** [comment]
> Hi Shang,
> The PTI procedure saves 2 outputs, the vector "w" which is used as the inversion for the input image, and the model itself after changing the weights to better suit the specified image.
> 
> The "run_PTI" method accepts an argument called "use_multi_id". If it is set to True, then PTI will create _One_ Model(Tuned StyleGAN) for all of the images. If it is set to False(Default) PTI will save several models, one model for each image.
> 
> Hope it answers your question,
> Daniel

**Comment by shang106121** [comment]
> > Hi Shang,
> > The PTI procedure saves 2 outputs, the vector "w" which is used as the inversion for the input image, and the model itself after changing the weights to better suit the specified image.
> > The "run_PTI" method accepts an argument called "use_multi_id". If it is set to True, then PTI will create _One_ Model(Tuned StyleGAN) for all of the images. If it is set to False(Default) PTI will save several models, one model for each image.
> > Hope it answers your question,
> > Daniel
Ok thanks, I get it
