### ISSUE TITLE
how to get more editing directions

### ISSUE THREAD

**Issue by JK737353** [danielroich/PTI#15]
Hi, thanks for your great work.
I notice that you said the editing directions you uploaded are  trained on the pretrained StyleGAN. If I want  more editing directions, what should I do?
Thank you.

**Comment by danielroich** [comment]
Hey @JK737353 
There are several ways to edit images using StyleGAN after the initial inversion done by PTI.
You can use directions from InterfaceGAN, GANSpace, Sefa, StyleCLIP, and many more amazing works.

Creating an editing direction on your own is a feasible task, nevertheless not an easy one. Therefore I would suggest searching for a framework from the ones I have mentioned above which manipulates the latent code to your desired need,
And if you don't find one, create one yourself using the InterfaceGAN framework for example

See https://github.com/orpatashnik/StyleCLIP or https://github.com/genforce/interfacegan for more information about editing frameworks

**Comment by molo32** [comment]
hi danielroich, can you tell me where to find the interfacegan latents for gender and glasses, the repository only has age smile pose.

**Comment by danielroich** [comment]
Hey @molo32 ,
I personally do not possess any more editing directions for InterfaceGAN. You can try to create ones on your own.
See https://github.com/genforce/interfacegan for more details.

A different option would be to use other editing techniques - such as GanSPACE, SeFa, StyleFlow and StyleCLIP 
Although I did not upload support for SeFa and StyleFlow, I have received messages from different users which combined the methods successfully

**Comment by shankarsivarajan** [comment]
[These](https://twitter.com/robertluxemburg/status/1207087801344372736) (also used [here](https://github.com/EvgenyKashin/stylegan2-distillation/tree/master/stylegan2directions)) seem to work well.

**Comment by molo32** [comment]
try to use the boundary of ffhq that are in
https://github.com/genforce/interfacegan/tree/master/boundaries
i turned them npy into pt
but it seems that it does not work, it modifies the face but it does it very badly.
to go from npy to pt just use torch.load and np.load.
am i missing something?

**Comment by danielroich** [comment]
Hey @molo32 ,
The reason why this does not work is because those boundaries were found based on StyleGAN1.
In this project we use StyleGAN2, which has a completely different latent space than StyleGAN1. Hence also different boundaries

The boundaries I have uploaded were trained on StyleGAN2, that's why they work
