### ISSUE TITLE
Noob - question missing something 

### ISSUE THREAD

**Issue by johndpope** [danielroich/PTI#16]
I got all the models. Environment is fine.
Code runs. I check the config…. Seems ok. But I don’t get anywhere using 2 scripts

scripts/run-pti.py

and evaluation python script.

![5C13D617-B277-4B07-AF6C-A61770882526](https://user-images.githubusercontent.com/289994/125771145-023cba85-6f83-4879-91b4-8d5bd2951646.jpeg)

I don’t see any output. 
I check output directories / but I don’t get any files spat out. I have an aligned folder with sequence of images of faces… 

![7EA68D9E-432C-4251-93DF-998235757354](https://user-images.githubusercontent.com/289994/125771174-54bb39c0-c60b-444d-83cd-8709e405eb71.jpeg)

**Comment by johndpope** [comment]
UPDATE 

found the images in the output/barcelona/.../single_images folder.

**Comment by danielroich** [comment]
Happy that you found it!

Note that the output's directory name - which on your run was "Barcelona", is decided by the configuration file.
In the parameter 'input_data_id ' under `configs/paths_config.py`. It is used to keep track of the experiments you run.
You can change it according to the input images title.
