### ISSUE TITLE
Where to download the out-of-domain images?

### ISSUE THREAD

**Issue by huiqu18** [danielroich/PTI#17]
Thanks for your great work! Could you please share the original out-of-domain images you collected?

**Comment by danielroich** [comment]
Hey @huiqu18,
The images I have used are scattered across the internet, Most of them are the top results when you search for the character.

Here are few example links:
[Joker]( https://www.google.com/search?q=joker&sxsrf=ALeKk00ODkKyeLLW7ss4U4QeuoVrfJw3rg:1627735906416&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjCufXjrI3yAhWB2-AKHSGdDdcQ_AUoAXoECAEQAw&biw=1536&bih=722#imgrc=T8t5ekFmydq_DM),  [Tyrion Lannister](https://www.google.com/search?q=tyrion+lannister&sxsrf=ALeKk00M6NLDWJbfLLjXBtVSrGy9M_vsoQ:1627736200197&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiHn4DwrY3yAhUvC2MBHb-5BJEQ_AUoAXoECAEQAw&biw=1536&bih=722#imgrc=A-iBfoa2Q39GXM) and [Lebron James](https://www.google.com/search?q=lebron+james&tbm=isch&ved=2ahUKEwjuoI_2rY3yAhUE0oUKHSLjCK4Q2-cCegQIABAA&oq=lebron+james&gs_lcp=CgNpbWcQAzIECCMQJzIECCMQJzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgQIABBDOggIABCABBCxA1Cw6AFYrPgBYOP6AWgAcAB4AIABfIgB0QmSAQM2LjaYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=lUgFYa6CAYSklwSixqPwCg&bih=722&biw=1536#imgrc=dYxj-hw_-jLxeM)

**Comment by huiqu18** [comment]
Thank you for your response.
