### ISSUE TITLE
Run PTI on 256*256 images

### ISSUE THREAD

**Issue by hyungkwonko** [danielroich/PTI#18]
Dear Daniel,
Thank you very much for the great work.
I am trying to apply PTI on my trained model which has 256 * 256 resolution.
Could you give me any tips on which part should I fix in the code?
Many thanks,

**Comment by hyungkwonko** [comment]
Sorry, I found it by myself.
Closing this issue.

**Comment by Shaoliu089** [comment]
> Sorry, I found it by myself. Closing this issue.

Hi, can you share where can I fix the code? I want to apply it to a 128*128 model. Thank you!

**Comment by hyungkwonko** [comment]
I am so sorry that it is too late to answer your question.
I found this as another person asked the same question with the link to here.

To answer your question, it is a bit long to explain how to use pretrained model with different dimension, you may want to refer to [my implementation](https://github.com/danielroich/PTI/commit/831153b960880f92267e27c8057b4b5824477c6e).
Specifically, you may want to refer to [w_projector.py](https://github.com/danielroich/PTI/commit/831153b960880f92267e27c8057b4b5824477c6e#diff-351a6431774b43844e335d40e1cc880a16a9dedde0abd1ea716bc05c12060ca5) which is an example for 256 dimension. You can apply this for your 128 dim model
Please read the code and reach me out if you have any more questions.
