### ISSUE TITLE
RuntimeError: ./pretrained_models/e4e_ffhq_encode.pt is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by mapleyuan** [danielroich/PTI#22]
hi, i got a error and i search the google it maybe the torch version prob. could u provide your torch version and my torch version as below.
torch==1.3.0
torchsummary==1.5.1
torchvision==0.4.1

RuntimeError: ./pretrained_models/e4e_ffhq_encode.pt is a zip archive (did you mean to use torch.jit.load()?)

**Comment by woctezuma** [comment]
>  torch==1.3.0

This is an old version.

In this issue https://github.com/pytorch/pytorch/issues/43766, someone mentions that `torch.jit.load()` does not even exist in version 1.7, and you are using version 1.3.
