### ISSUE TITLE
it's any method to speed up?

### ISSUE THREAD

**Issue by mapleyuan** [danielroich/PTI#25]
hi guys, i want to make it test online.but it's too slow because the embedding generator need about 35 mins.

**Comment by danielroich** [comment]
Hey @mapleyuan 
Did you run the PTI method using CPU?
If you have GPU make sure you configure the inference correctly, by default PTI uses GPU. While using GPU you should receive results after ~2 minutes and afterwards each edit is instant.

Also check if you are using the method correctly, even if you are using CPU it should run for about 10 minutes, not 35.

If you cannot access GPU resources, you could try to scale up the code by using parallel tuning, I haven't tried it so far but it sounds the best option considering you have only CPU available. It will require making code changes.

Daniel

**Comment by mapleyuan** [comment]
hey @danielroich, yeah i Have used cpu to run it and i test several times about 35mins. I will try run it on gpu online machines, 

but I still have meet the problem how to make it faster. is it impossible to control it in few seconds about 5 second ?

I am a new hand Could you give me more detail advise? thx!

**Comment by mapleyuan** [comment]
@johndpope I had reduced the steps but the result is bad 0.0

**Comment by johndpope** [comment]
Just use google cloud or upgrade gpu..... welcome to modern day machine learning.
