### ISSUE TITLE
This needs updating with readme

### ISSUE THREAD

**Issue by johndpope** [danielroich/PTI#28]
https://github.com/danielroich/PTI/blob/7da3f22f8077c6930afa13186e3f80dcf734779b/models/StyleCLIP/optimization/run_optimization.py#L29

**Comment by danielroich** [comment]
Thanks! :)
Will be updated

**Comment by johndpope** [comment]
I maybe doing something wrong and or tied / but when I point the python optimization/run_optimization.py  code at a presaved PTI pytorch latent 
it seems to be getting the e4e ??? That would only make sense if the embeddings were saving to wrong directory....??


**PTI**
 python optimization/run_optimization.py --latent_path=/home/jp/Documents/gitWorkspace/e4e/embeddings/images/e4e/1/0.pt --description "drug fiend"
![00020](https://user-images.githubusercontent.com/289994/133928368-bda35648-e18b-4d90-a356-3759f5378ea1.png)

 python optimization/run_optimization.py --latent_path=/home/jp/Documents/gitWorkspace/PTI/embeddings/images/PTI/1/0.pt --description "drug fiend"

![00000](https://user-images.githubusercontent.com/289994/133928256-0545eacc-1a4e-45a8-bf97-8e53df9d998a.png)


 python optimization/run_optimization.py --latent_path=/home/jp/Documents/gitWorkspace/PTI/embeddings/images/SG2_plus/1/0.pt --description "drug fiend"

![00000](https://user-images.githubusercontent.com/289994/133928208-beb46a95-6d91-404e-85e6-d6876b154f98.png)

**Comment by Andy010902** [comment]
@johndpope Hi, I need your help! 
When I do "python run_optimization.py" in the directory "./optimization",I get "error: cann't import name 'ensure_checkpoint_exists' from 'StyleCLIP.global_directions.utils' (./utils/_init_.py)", then I search for  'ensure_checkpoint_exists' in the entire project, then all about it are located in './run_optimization.py'.
 And there is nothing in ./models/StyleCLIP/global_dirctions/utils/_init_.py

So, I just wonder if there are something lost in the github.

**Comment by johndpope** [comment]
sorry Andy, when nvidia-labs abandoned tensorflow in favour of pytorch - I no longer work with tensorflow.

Doing a search for that specific function name on github - returns many results. - https://github.com/search?q=ensure_checkpoint_exists+styleclip&type=code

I would abandon this repo for one in favour of torch / see results above. you can see in requirements
