### ISSUE TITLE
How many images have been tried at most to train together?

### ISSUE THREAD

**Issue by laolongboy** [danielroich/PTI#33]
Thans for your contribution. How many images have been tried at most to train together? Ideally, each picture corresponds to one pivotal finetuned stylegan. I have 2w+ images with different IDs and quality of images are different. What if I train them together to get one stylegan?

**Comment by danielroich** [comment]
Hey @laolongboy,
Personally, I have tried 64 at most while the locality regularization is active. Of course you can invert even more identities if you want.

You can use PTI on those 2 identities together and receive only one StyleGAN. Which will incorporate both identities. To do so you need to use the MultiIDCoach by passing True to the use_multi_id_training variable in the run_pti script.

You should receive results as if you have used PTI on each of them separately, but with only one StyleGAN

**Comment by laolongboy** [comment]
> 

Thanks, I will try and update the results.

What's more, do we need to reseek the InterfaceGan's attrbute boundarys? or we can directly use the boundarys detected  in the original stylegan space?

**Comment by danielroich** [comment]
The best part of the PTI process is that you can directly use the boundaries detected in the original StyleGAN space. Not only InterfaceGAN, but also GANSpace and StyleCLIP, and much more. The PTI process together with the regularization affects only the identity attribute in a very local environment.
