### ISSUE TITLE
inversion on whole body images

### ISSUE THREAD

**Issue by onyekaokonji** [danielroich/PTI#36]
I'm trying to perform inversion on whole body images as opposed to faces. Looking at the inference notebook you shared, I'm guessing the preprocessing function which receives input from align_faces will need a new function called align_body (for example) to provide input for a body image. 

Or will the best solution be to skip the preprocessing step all together?

**Comment by onyekaokonji** [comment]
Thank you! I eventually found StyleGAN-Human's repo in which they designed a function for PTI inversion of body images. Of course using an alignment function for bodies.

**Comment by sawk1** [comment]
> Thank you! I eventually found StyleGAN-Human's repo in which they designed a function for PTI inversion of body images. Of course using an alignment function for bodies.

Hello, im trying to find it, but bad luck so far(

**Comment by hajiarab1988** [comment]
> > Thank you! I eventually found StyleGAN-Human's repo in which they designed a function for PTI inversion of body images. Of course using an alignment function for bodies.
> 
> Hello, im trying to find it, but bad luck so far(

https://github.com/stylegan-human
