### ISSUE TITLE
Effect of lpips type

### ISSUE THREAD

**Issue by luchaoqi** [danielroich/PTI#46]
Hello, 

I find that the option of `lpips_type = 'alex'` tend to affect my inversion results:
with `lpips_type = 'alex'`, it introduces undesirable checkerboard/noise-like artifact which gives me a sense of overfitting (input left and reconstruction right)
![image](https://github.com/danielroich/PTI/assets/46330265/735850f1-e9a2-4e63-bcd4-d016b291f1fb)
![image](https://github.com/danielroich/PTI/assets/46330265/eba717fb-6a83-4db4-b540-bcbb5ab4b8d0)
with `lpips=type='vgg'`, results are smoother which gives me a sense of underfitting:
![image](https://github.com/danielroich/PTI/assets/46330265/8f816f59-6b40-405f-a144-c2a4ef4c749c)
![image](https://github.com/danielroich/PTI/assets/46330265/210ed196-2621-4b44-9f68-0f60846efb66)
you may need to zoom-in a bit to tell the difference.
any suggestions in this case? do I need to tune options like `LPIPS_value_threshold = 0.06` to find a sweet point between this trade-off?

**Comment by danielroich** [comment]
Hi @luchaoqi,
playing with the hyper-parameters of the L2 and the lpips as you suggested is the best option in my opinion.
Moreover, you might change the convergence criteria in the configuration file as well so the current alexnet would not overfit
